= Czego nauczyliśmy sie w #1 tygodniu

== Recenzje kodu

Wzajemne recenzje sa ważnym elementem pracy nad projektem.

* Pozwala wyłapać niektóre błędy
* Pomaga w nauce

Recenzja kodu jest bardzo czasochlonna, dlatego na kursie pre java academy, gdy uczestników jest kilkudziesięciu najlepiej jest jej nie robic, jesli tylko mozna tego uniknac i skupić się na recenzji najlepszych prac.

* Dyskwalifikacja za przewinienia:
** Nie kompiluje się 
** Nie buduje się
** Nie działa 
** Nie ma testów 
** Brak podstawowych funkcjonalności
 
* Sprawdzanie projektu: 
** Spradzamy POM i dependencies (jakich bibliotek uzywa) 
** Sprawdzamy strukture pakietow
** Sprawdzamy nazwy klas 
** Sprawdzamy java docsy 
** Na koniec sprawdzamy sam kod 

* Sprawdzenie kodu rozpoczynamy od analizy commitow
** Pozwala ona przesledzic sposob myslenia autora
** Pokazuje ktore klasy byly najczesciej zmieniane

NOTE:  ‘squash commits’ Gdy piszemy projekt commitujemy tylko znaczace zmiany, zeby ulatwic robote recenzentowi, albo ‘splaszczamy’ malo znaczace commity. 
https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc 

== Linux

* Podstawowe komendy
* poruszanie sie po systemie
* instalowanie programow
* man - Bardzo wazna komenda, pozwala przegladac instrukcje (man od 'manual') do wszystkich innych komend (i programow) w systemie
* top - pokazuje obciazenie systemu przez procesy (procek, pamięć)
* tree - pokazuje drzewo katalogow i plikow

== Warsztaty
Przygotowywalismy zadania dla siebie nawzajem do zrobienia w piatek
Samo robienie zadan, to proces bardzo pracochlonny, przygotuj sie na kilka-kilkanascie godzin pracy, by przygotowac zadania do zobienia przez grupe w ciagu 45min. Plus taki, ze mozna sie w tym czasie troche nauczyc.
Sporym problemem okazalo sie skomponowanie opisu zadań w jednoznaczny i precyzyjny sposób.
Trudno wyestymować ile czasu rozwiazanie zadania zajmie grupie.

=== Co ciekawego bylo na warsztatach:

* Typy generyczne:
** Skladnia generykow 
** Przechowanie opakowanego typu jako Object i rzutowanie go na typ generyczny w metodach podajacych go na zewnatrz
 
* Wyjatki: 
** Chained exceptions https://www.baeldung.com/java-chained-exceptions 
** e.getCause() - Mozemy ustawiac wyjatek jako przyczynę innego wyjatku 
*** Zastosowanie – np jesli lapiemy kilka różnych wyjątków,  możemy złapany wyjątek opakować w nasz wyjątek, ktory rzucamy dalej. Wtedy analizujac nasz wyjatek mozemy sprawdzic jaki wyjatek go wywołał. 

* Collections: 
** TreeMap  
*** Bardzo przydatna struktura 
*** Mapa w której klucze sa posortowane 

== Obiektowość  

* Enkapsulacja:
** gettery i settery to antywzorzec 
*** Stosować tylko jesli framework wymaga 
*** Zamiast tego znaczące (w sensie odpowiednio nazwane) metody które pozwalają modyfikować stan obiektu w kontrolowany sposób.

== Trivia:
[qanda]
Przyklad dekoratora w javie::
Collections

Ile metod w klasie `Object`?::
11

Co rozszerza klasę `Vector`?::
Stack 

Ktora nastepna wersja javy bedzie wersją LTS (Long Time Support)::
17
 
 
